POST http://localhost:8080/users
content-type: application/json

{
  "name": "Jovana",
  "email": "todorovicdrago1@gmail.com",
  "dob": "1997-06-05T15:04:05Z",
  "weight": 60,
  "height": 170,
  "gender": "female"
}